### PR TITLE
🐛 Fix upload

### PR DESCRIPTION
**Pull request by falexwolf**

### CODE REVIEW

**Comment by Koncopd** [comment]
Hm, strange that the tests didn't fail before.

**Comment by Koncopd** [comment]
Ah, ok, i see why it still worked fine
image

**Comment by Koncopd** [comment]
image

**Comment by falexwolf** [comment]
Yes, I was also confused that the tests didn't fail. We only just found out in the web platform.

Could you add a test that would have made it fail?

**Comment by Koncopd** [comment]
I can add, but not now. Maybe tmr.

**Comment by falexwolf** [comment]
Not urgent!

**Pull request merged**
