### PR TITLE
:construction_worker: Update docs to clarify sign up and log in

### PR DESCRIPTION
**Pull request by lawrlee**
Updated docs for clarity in the `Sign up and log in user` section. Just suggestions so please review and edit if needed!

### CODE REVIEW

**Review by sunnyosun — APPROVED** [review]
Thank you for the improvement! This looks great!

**Comment by sunnyosun** [comment]
CI failure seems to be related to issue on superbase server, should be fine in a bit. Feel free to merge it @lawrlee!

**Comment by lawrlee** [comment]
Ok @sunnyosun! I was worried about the failed check.

**Comment by falexwolf** [comment]
Great, Lawrence! 😄

**Comment by falexwolf** [comment]
This fails because the email address doesn't exist: `testuser1@ln.setup.ai`

It wasn't executed it before, but this PR started to execute it.

**Comment by falexwolf** [comment]
Fixed here: https://github.com/laminlabs/lamindb/commit/b0c773185189d742790ba584a34d1383903a5b0f

**Pull request merged**
