### PR TITLE
✨ Error when renaming internal features and labels

### PR DESCRIPTION
**Pull request by sunnyosun**
When to error:
1. If a feature is an internal feature, aka it is a member of a featureset.
    Screenshot 2024-10-18 at 15 55 42
2. If a label is an internal label, aka it is associated with an internal feature.
    Screenshot 2024-10-18 at 15 55 33

To bypass the renaming error:
1. `artifact.features.make_external(feature)`: remove feature from all featuresets.
2. `artifact.labels.make_external(label)`: keep the label associated with artifacts, but remove set `feature=None` in the link tables. This label will no longer associated with any internal faetures.

Full renaming UX:
https://lamin.ai/laminlabs/lamindata/transform/u1s4bAB3sliY0000

### CODE REVIEW

**Comment by falexwolf** [comment]
Can you please add more production-ready screenshots or use pretty text snippets? This is a big new feature that needs a high-quality announcement in the docs.

Also: there is a grammatical error in the user dialogue which makes it feel somewhat haphazard:

image

I know this is well thought but the PR overall doesn't give the appearance.

**Comment by falexwolf** [comment]
The other big thing that misses is the definition of "internal" vs. "external" feature. It's nowhere defined in the docs. So, guides & API docs should be updated. Even the PR title can't be understood if this isn't documented.

**Comment by falexwolf** [comment]
> what error?

It's "rename a feature" not "rename feature".

For the second line, one could maybe do: "These artifacts contain the old name of the feature: [...]"

Because "not validated" sounds a bit technical and doesn't explain specifically what the problem is.

**Comment by sunnyosun** [comment]
Feel free to reword the logging if you don't like it, I asked for your review before.

**Comment by falexwolf** [comment]
@sunnyosun, instead of screenshots, can you put really pretty formatted text messages? This is one of the most important features of the past months and we should have a polished announcement for it.

I also want to use this in the lakehouse tutorial (without this feature, lamindb wouldn't be a lakehouse).

**Comment by sunnyosun** [comment]
> @sunnyosun, instead of screenshots, can you put really pretty formatted text messages? This is one of the most important features of the past months and we should have a polished announcement for it.
> 
> I also want to use this in the lakehouse tutorial (without this feature, lamindb wouldn't be a lakehouse).

Done!

**Pull request merged**
