### PR TITLE
✅ Record number of objects, test hashes and folder properties

### PR DESCRIPTION
**Pull request by falexwolf**

### CODE REVIEW

**Comment by falexwolf** [comment]
Interestingly, the suffix has an impact on the hash of the directory on my Mac, but not on the GA worker:
image

**Comment by falexwolf** [comment]
No, I can't confirm this by testing in our hash tests:
```
def test_compute_hash():
    files = [
        # file_content, hash, chunk_size, hash_type
        ("a", "DMF1ucDxtqgxw5niaXcmYQ", None, "md5"),
        ("b", "kutf_uauL-w61xx3dTFXjw", None, "md5"),
        ("abc", "kAFQmDzST7DWlj99KOF_cg", None, "md5"),
        ("a", "DMF1ucDxtqgxw5niaXcmYQ", 1, "md5"),
        ("b", "kutf_uauL-w61xx3dTFXjw", 1, "md5"),
        # the last case here triggers multi-chunk compute with sha1
        ("abc", "p0EbDbQEP1wS-Tw6TuBjKS", 1, "sha1-fl"),
    ]
    for content, hash, chunk_size, hash_type in files:
        filepath = Path("file_1")
        filepath.write_text(content)
        computed_hash, computed_hash_type = hash_file(filepath, chunk_size=chunk_size)
        assert computed_hash == hash
        assert computed_hash_type == hash_type
        filepath.unlink()
```

**Comment by Koncopd** [comment]
Hi, i saw some comments about problems with hashes, but can't see them anymore. Was it resolved.

**Comment by falexwolf** [comment]
> Hi, i saw some comments about problems with hashes, but can't see them anymore. Was it resolved.

Yes, it's resolved! I just had forgotten to sort the output of `.glob(*)` before hashing it.

**Pull request merged**
