### PR TITLE
🚸 Simplify installation & API overview

### PR DESCRIPTION
**Pull request by falexwolf**
## Installation

Before:
```bash
pip install "lamindb[aws,bionty,jupyter,ourprojects]"
```

After:
```bash
pip install "lamindb[bionty,jupyter]"
```

## Docs

Before | After
--- | ---
image | image

## Materials

- https://github.com/laminlabs/lamindb/issues/2301

### CODE REVIEW

**Comment by Koncopd** [comment]
But why the submodules were removed?

**Comment by Koncopd** [comment]
This will also break a ton of CI scripts across the repos.
I really don't like that aws dependency is installed by default now, it is very problematic because sometimes people because sometimes it can break existing environments, so if people have their environment with `s3fs` etc configured, it is better not to touch it.

**Comment by Koncopd** [comment]
I think such things should be discussed before merging.

**Comment by Koncopd** [comment]
Ok, about breaking i am probably not right, it was some time before, but was simplified.

**Comment by Koncopd** [comment]
No, thinking about this, it can still cause problems.

**Comment by falexwolf** [comment]
> No, thinking about this, it can still cause problems.

What problems can it cause? I think it will reduce problems!

Assume that somebody has an incompatible version of s3fs installed. If they forget to provide the `aws` extra during installation, they'll never get feedback on clashing version requirements.

Now, they'll immediately get feedback if something clashes with what lamindb expects for `aws`.

I believe this might have been the cause of some bugs where people didn't notice anything until they call `.load()` or `.cache()` and then get a cryptic error and don't know what to do. That error would have been avoided if `aws` is simply part of `lamindb`.

**Comment by falexwolf** [comment]
> But why the submodules were removed?

`findrefs` is deprecated in favor of `ourprojects`.

`omop` isn't a real use case; this requires much more discussion and is at this point confusing. There is still a link to https://omop.lamin.ai/

The docs job was beyond 6 min before this; now it's back to 3 min because omop is so huge.

**Comment by falexwolf** [comment]
> I think such things should be discussed before merging.

Yes, I know. Sorry, I discussed it 4 times with myself and then considered it's high probability that we actually want this and be done with it so that I could finalize a downstream dependency at the same time.

**Comment by Koncopd** [comment]
> What problems can it cause? I think it will reduce problems!

Yes, thinking yet again, you are right here. I had problems on sagemaker, where it worked with a given environment but broke with `lamindb[aws]`, but it was long time ago, there are no sagemaker environments like this anymore and the structure of aws deps changed.
The only thing i don't like it having `boto3` here https://github.com/laminlabs/lamindb-setup/blob/8426994be65f5a2cfded28d241c402e5ac207e7b/pyproject.toml#L32 that is used nowhere in `lamindb`, but was added just not to break existing environments where `boto3` is installed and used.

**Comment by Koncopd** [comment]
If we have clients in the future that rely only on `gcp`, we will need to reintroduce `aws` extra i think.

**Comment by falexwolf** [comment]
> If we have clients in the future that rely only on gcp, we will need to reintroduce aws extra i think.

I don't think so based on this argument from the issue

> While purely local usage or purely GCP wouldn't need it, it seems that these are edge cases. Almost anybody will at some point want to pull something from an S3 bucket. 

Also people on GCP will at some point want to access data from some AWS bucket. And AFAIK boto3 and s3fs aren't big; these are just a few python files.

**Comment by Koncopd** [comment]
Yes, this makes sense, you are right.

**Pull request merged**
