### PR TITLE
✅ Add tests for zarr ingest and load

### PR DESCRIPTION
**Pull request by Koncopd**
subj

### CODE REVIEW

**Comment by Koncopd** [comment]
@falexwolf 
```
/home/runner/work/lamindb/lamindb/.nox/build-3-9/lib/python3.9/site-packages/lnschema_core/_core.py:docstring of lamindb.schema.DTransform.pipeline_run_id:1:py:class reference target not found: lnschema_core.PipelineRun
nox > Command lndocs  failed with exit code 2
```
There is a problem with the docs of `lamindb.schema.DTransform`, but i can't find the reason.

**Comment by falexwolf** [comment]
This is just in the docs... I did a rename `PipelineRun` -> `Run` and the docs are pointing to that most recent version. Hm.

**Comment by falexwolf** [comment]
This can only happen for cross-referencing docs, which we only have for very fundamental things like the core schema module.

I'll think about a longterm solution but right now will just quickly migrate lamindb.

**Comment by Koncopd** [comment]
@falexwolf thx for updating, i was on the way home, so couldn't do myself.

**Pull request merged**
