### PR TITLE
✨ Add explicit remote sqlite instance locking to write operations

### PR DESCRIPTION
**Pull request by Koncopd**
subj

### CODE REVIEW

**Comment by Koncopd** [comment]
@falexwolf is there a reason why the sqlite file is update for every record in delete https://github.com/laminlabs/lamindb/blob/38b3e604f85a0920f73b46d05c758cb94fecb704/lamindb/_delete.py#L79 ?

**Comment by Koncopd** [comment]
This requires a release of lndb-setup.

**Comment by falexwolf** [comment]
Re: https://github.com/laminlabs/lamindb/pull/447#issuecomment-1399550932

No, there isn't! It shouldn't!

**Review by falexwolf — APPROVED** [review]
This is good to merge from my end!

**Comment by Koncopd** [comment]
I will fix then `delete` and then merge this.

**Pull request merged**
