### PR TITLE
:recycle: Inherit `IngestObject` and `IngestPipelineRun` from `IngestEntity`

### PR DESCRIPTION
**Pull request by bpenteado**
See title.

### CODE REVIEW

**Comment by bpenteado** [comment]
@falexwolf you should be able to catch errors inside those functions and write the cleanup functionality easily within `IngestEntity`.

**Comment by bpenteado** [comment]
Happy to discuss if needed!

**Comment by bpenteado** [comment]
Sorry for the delay here folks. Immigration was a massive headache… But got it done.

**Comment by falexwolf** [comment]
Wow, Bernardo! Awesome! :star-struck:

Please get some rest!

**Pull request merged**
