### PR TITLE
⬆️  Upgrade and rename `lndb_setup` to `lndb` (v0.32.4)

### PR DESCRIPTION
**Pull request by bpenteado**

### CODE REVIEW

**Review by falexwolf — APPROVED** [review]
This is all good and just requires renaming lndb_setup to lndb in bionty!

**Comment by sunnyosun** [comment]
Can this be merged soon?

**Comment by bpenteado** [comment]
@sunnyosun I had to get out for an appointment but will be back in an hour or so. Will finalize all the upgrades quickly and merge then.

**Comment by bpenteado** [comment]
> 

Good catch Sergei, thank you! 

@falexwolf, @sunnyosun - should we just comment out the notebook for now? Or is a more fundamental fix warranted?

**Comment by Koncopd** [comment]
It is a conflict between new matplotlib and scanpy.

**Pull request merged**
