### PR TITLE
🔥 Remove `lamin` dependency

### PR DESCRIPTION
**Pull request by falexwolf**

### CODE REVIEW

**Comment by Koncopd** [comment]
`from lamindb.setup import import lazy` in the `stream` notebook, invalid syntax.
in addition, `lazy` is not (or should not) be in `lamindb.setup`, it is in `lamindb`.

**Comment by falexwolf** [comment]
Thank you!

**Comment by Koncopd** [comment]
Actually i am not sure this is a good approach to the syntax errors in `nbproject`, but also i don't know how to treat them better.

**Comment by falexwolf** [comment]
It's very much an edge case that's not important right now, I'd say!

I just generated them doing bulk replacement of strings.

**Comment by Koncopd** [comment]
I am also confused a bit now, what is the CLI command name then?

**Comment by Koncopd** [comment]
Now that is an interesting CI fail.
On the first `import lamindb` in the `lazy-loading` notebook it tries to connect to the posgres db from the previous notebooks due to `_check_migrate` in the `__init__.py` and fails.

**Comment by falexwolf** [comment]
The CLI command name is `lamin`.

**Comment by Koncopd** [comment]
But it is still lndb https://github.com/laminlabs/lndb/blob/1f7d4ef90111926f3cff178f40d3a72247ba0561/pyproject.toml#L60 ...

**Comment by falexwolf** [comment]
> Now that is an interesting CI fail. On the first `import lamindb` in the `lazy-loading` notebook it tries to connect to the postgres db from the previous notebooks due to `_check_migrate` in the `__init__.py` and fails. This is the problem we discussed during the meeting today.

Hmmmmm. OK. I ran into this problem also when trying to blindly replace `lndb` with `lamindb.setup` in the `lndb` repository.

**Comment by falexwolf** [comment]
> But it is still lndb https://github.com/laminlabs/lndb/blob/1f7d4ef90111926f3cff178f40d3a72247ba0561/pyproject.toml#L60 ...

What you show is for backward compat. The new CLI is defined within `lamindb` (see this PR).
image

**Comment by falexwolf** [comment]
> Now that is an interesting CI fail. On the first `import lamindb` in the `lazy-loading` notebook it tries to connect to the postgres db from the previous notebook due to `_check_migrate` in the `__init__.py` and fails. This is the problem we discussed during the meeting today.

Unfortunately, I don't fully understand why this happens - it's a bit late, but if you think you understand what's going on here, I'd appreciate a brief Slack huddle. :)

**Comment by Koncopd** [comment]
And we can't even avoid this problem by importing `setup` from `lamindb.setup` at first like before with `lndb`, because `_check_migrate` in the main `__init__.py` will be triggered anyways.

**Comment by falexwolf** [comment]
It shouldn't trigger `_check_migrate` if the instance is not setup!

**Comment by Koncopd** [comment]
Lets talk.

**Comment by falexwolf** [comment]
Calling you on Slack!

This is what's currently running in __init__.py:
```
if (
    not _current_instance_settings_file().exists()
    or _setup_settings.instance.storage.root is None
):
    _logger.warning(
        "You haven't yet setup an instance using the CLI. Please call"
        " `lamindb.setup.init()` or `lamindb.setup.load()`."
    )
    _instance_setup = False
else:
    _instance_setup = True
    _check_migrate(usettings=_setup_settings.user, isettings=_setup_settings.instance)
```

**Pull request merged**
