### PR TITLE
⚡️ Improvements to `save_tiledbsoma_experiment`

### PR DESCRIPTION
**Pull request by Koncopd**
Read local adatas in backed mode for writing to a tiledbsoma store.

### CODE REVIEW

**Comment by falexwolf** [comment]
Are we sure we want to buy in this complexity? If so, we need a test. I'd rather just keep it the way it was.

**Comment by Koncopd** [comment]
This is the correct way, it is how it is done tin `tiledbsoma` also. And it is tested already by the existing tests.

**Comment by Koncopd** [comment]
No complexity added from our side here, everything is already implemented in `tiledbsoma` itself, i mean it accepts backed anndatas without any problems.

**Comment by falexwolf** [comment]
Ok!

**Pull request merged**
