### PR TITLE
♻️ Use Click for CLI

### PR DESCRIPTION
**Pull request by falexwolf**
- https://github.com/laminlabs/lamin-cli/pull/22

### CODE REVIEW

**Comment by falexwolf** [comment]
Running tests against the rebased lamin-cli!

**Comment by falexwolf** [comment]
@chaichontat - I think everything works with the exception that you're not treating return codes correctly

image

The CLI should return an error code when it fails. Right now it returns 0.

**Comment by chaichontat** [comment]
> @chaichontat - I think everything works with the exception that you're not treating return codes correctly
> 
> image
> The CLI should return an error code when it fails. Right now it returns 0.

```python
import os
from subprocess import run

env = os.environ
env["LAMIN_TESTING"] = "true"
print(run("lamin save x.ipynb", env=env, shell=True).returncode)
```
ValueError: Notebook cannot be empty. It must have at least a title cell.

Return code: 1

**Comment by falexwolf** [comment]
Why is the return code in the pytest session than `0`?

image

**Pull request merged**
