### PR TITLE
🚸 Enable autocompletion for inherited methods in Jupyter

### PR DESCRIPTION
**Pull request by Koncopd**
https://github.com/laminlabs/lnschema-core/pull/447
Fix https://github.com/laminlabs/lamindb/issues/2122

### CODE REVIEW

**Comment by Koncopd** [comment]
@falexwolf could you take a brief look at this pls when you have time. https://github.com/laminlabs/lnschema-core/pull/447
This solves the problem of not autocompleting inherited methods in jupyter (see https://github.com/laminlabs/lamindb/issues/2122). This PR fixes the problem but i am a bit worried that it can cause problems for the docs. I don't see any problems now but you know more about this.

**Comment by Koncopd** [comment]
Also replace `exclude_instance_methods = IS_RUN_FROM_IPYTHON` with `exclude_instance_methods = "sphinx" not in sys.modules`

**Comment by falexwolf** [comment]
Looks all good to me, Sergei!

**Review by falexwolf — APPROVED** [review]

**Comment by Koncopd** [comment]
Ok, thx!

**Pull request merged**
