### PR TITLE
♻️ Move storage related code to `lndb_storage`

### PR DESCRIPTION
**Pull request by Koncopd**
- https://github.com/laminlabs/lndb-storage/pull/4

### CODE REVIEW

**Comment by falexwolf** [comment]
This is great, @Koncopd! Could you also move the "faq/storage.ipynb" notebook? I'm not even sure it's needed anywhere given that API might be completely out-of-date.

But before trashing, it'd be nice to come up something comparable for the storage API that's actually put to use.

**Comment by Koncopd** [comment]
@falexwolf Thanks. I was unsure what to do with this notebook. If it is moved, then i can also remove file and object reimports.

**Comment by falexwolf** [comment]
Yes, please move it!

**Comment by Koncopd** [comment]
Docs are failing with
`/home/runner/work/lamindb/lamindb/_docs_tmp/guide/run.ipynb:20004:py:class reference target not found: lamindb.schema.Run`
Not sure what happens there.

**Comment by falexwolf** [comment]
Strange that it didn't hit @sunnyosun - she removed it from `lamindb.schema`. 🤷

**Comment by falexwolf** [comment]
I'm fixing the remaining docs issues in another PR and then this will pass, too.

**Pull request merged**
