### PR TITLE
💄 Strip `NotebookNotSaved` from report after `ln.finish()`

### PR DESCRIPTION
**Pull request by Koncopd**

### CODE REVIEW

**Comment by falexwolf** [comment]
Problem is that this will also strip the output of any other tool that uses finish, say wandb

**Comment by falexwolf** [comment]
Two ways of resolving: (1) add more constraints that account for the lamindb namespace (2) require it to be the last cell

Can you check whether there is such a requirement within ln.finish to be called in the last cell if it's the global Context object?

I believe we had this for publish() in nbproject and I'd say it makes only sense to have it; doesn't it?

**Comment by Koncopd** [comment]
> Problem is that this will also strip the output of any other tool that uses finish, say wandb
Hm, no, why do you think so?

**Comment by falexwolf** [comment]
Ok, then good to merge! :D

**Pull request merged**
